### ISSUE TITLE
Can't compile GROMACS/nonbonded_benchmark according to instructions

### ISSUE THREAD

**Issue by stain** [bioexcel/bioexcel-exascale-co-design-benchmarks#2]
Compiling GROMACS/nonbonded_benchmark seem to need the regression tests.

/GROMACS/nonbonded_benchmark/gromacs_source_code [README](https://github.com/bioexcel/bioexcel-exascale-co-design-benchmarks/blob/master/GROMACS/nonbonded_benchmark/README.md) says

> Build exactly as you would build a production version of GROMACS.  See
> the INSTALL file in the gromacs_source_code subdirectory for details.

However this does not work, as it tries to download
http://gerrit.gromacs.org/download/regressiontests-2020.tar.gz
which is currently 404.  Trying `-DREGRESSIONTEST_DOWNLOAD=OFF` does not
work either as `gmxtest.pl` is missing.

We should not have HTTP downloads in the the benchmark code.

Suggested quick fix is to modify README to suggest disabling regression tests:

    cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=OFF -DGMX_BUILD_MDRUN_ONLY=ON -DBUILD_SHARED_LIBS=off

**Comment by stain** [comment]
See also #5 - I needed `cmake .. -DGMX_BUILD_OWN_FFTW=OFF -DREGRESSIONTEST_DOWNLOAD=OFF -DGMX_BUILD_MDRUN_ONLY=on -DBUILD_SHARED_LIBS=off -DGMX_EXTERNAL_TNG=on -DGMX_USE_TNG=off`

**Comment by mabraham** [comment]
Turning off gmx_use_tng should quiet all such issues. One cannot usefully build only mdrun.

**Comment by mabraham** [comment]
> Trying -DREGRESSIONTEST_DOWNLOAD=OFF does not work either as gmxtest.pl is missing.

Ah, that's a longstanding bug that nobody has reported. It works if it's always been off, but once on it doesn't turn off properly. I'll fix that in GROMACS proper, and document against using REGRESSIONTEST_DOWNLOAD here.
