### ISSUE TITLE
Unknown how to compile CP2K/kernel-benchmark

### ISSUE THREAD

**Issue by stain** [bioexcel/bioexcel-exascale-co-design-benchmarks#3]
"How to compile" and "How to run" is  blank in [CP2K/kernel-benchmark/README](https://github.com/bioexcel/bioexcel-exascale-co-design-benchmarks/blob/master/CP2K/kernel-benchmark/README.md)

Thus I don't know how to compile or run this benchmark.

**Comment by aproeme** [comment]
Added :-)
