### ISSUE TITLE
Need rough guidance on expected runtime

### ISSUE THREAD

**Issue by stain** [bioexcel/bioexcel-exascale-co-design-benchmarks#6]
It would be helpful if the README can show roughly how long these tests are meant to run on different configurations, and what are the minimum requirements (e.g. 16 GB RAM).

For instance `CP2K/whole-application-benchmark` with `mpirun -n 1` locally looks like it could run for hours, while `GROMACS/kernel_microbenchmark/` finishes in microseconds.

**Comment by mabraham** [comment]
I added that to kernel_microbenchmark/README.md

**Comment by aproeme** [comment]
Also added for CP2K whole-application and kernel benchmarks
