### ISSUE TITLE
Add script for downloading HADDOCK data file

### ISSUE THREAD

**Issue by stain** [bioexcel/bioexcel-exascale-co-design-benchmarks#7]
Ideally it should confirm the checksum, or it could do `curl http://.../ | tar gzf - ` to unpack on the fly (hoping for the best)

**Comment by mabraham** [comment]
Any thoughts here @rvhonorato ?

**Comment by mabraham** [comment]
https://github.com/bioexcel/bioexcel-exascale-co-design-benchmarks/tree/master/HADDOCK seems to cover this question
